image:
  - name: 'test'
    path: './image/some/'
    url: ''
    group: ''
  - name: 'test'
    path: './image/some/'
    url: ''
  - name: 'A-H.A占领战'
    path: './image/some/'
    url: 'https://i0.hdslb.com/bfs/article/9eaa1ecf9deba014aea8cd3578802b4471f64434.png@942w_1088h_progressive.webp'
    group: '1'
  - name: 'A-H.A占领战1'
    path: './image/some/'
    url: 'https://i0.hdslb.com/bfs/article/ffb0cbb7832e8d2202a85e46ead345ddeff42e07.png@942w_597h_progressive.webp'
    group: '1'
  - name: 'test'
    path: './image/student_rank/'
    url: ''