image:
  - name: 'test'
    path: './image/some/'
    url: ''
    group: ''
    type: "vertical" # horizen or vertical
    source: '1'
  - name: 'test'
    path: './image/some/'
    url: ''
    source: '1'
  - name: 'test'
    path: './image/student_rank/'
    url: ''
    source: '1'
  - name: 'test'
    path: './image/student_rank/'
    url: ''
    source: '1'
  - name: '夏'
    path: './image/student_rank/'
    url: 'https://i0.hdslb.com/bfs/article/e351ab58007099761039096419318140425535005.png@1256w_690h_!web-article-pic.avif'
    source: '1'
  - name: '泳装日富美'
    path: './image/student_rank/'
    url: 'https://i0.hdslb.com/bfs/article/8e8782ca7fa82234ed04683971d713f0425535005.png@1256w_554h_!web-article-pic.avif'
    source: '1'
  - name: '芹香'
    path: './image/student_rank/'
    url: 'https://i0.hdslb.com/bfs/article/2bf7b2116d15bf31e410287d7c9f61d1425535005.png@1256w_556h_!web-article-pic.avif'
    source: '1'