image:
  - name: 'test'
    path: './image/some/'
    url: ''
    group: ''
  - name: 'test'
    path: './image/some/'
    url: ''
  - name: 'test'
    path: './image/student_rank/'
    url: ''
  - name: '女仆装柚子'
    path: './image/student_rank/'
    url: 'https://i0.hdslb.com/bfs/article/bbc564a7ca23c963f8253ba1d2ef541d36208a5c.png@942w_489h_progressive.webp'
  - name: '女仆爱丽丝'
    path: './image/student_rank/'
    url: 'https://i0.hdslb.com/bfs/article/4cfca10789c64184111c6fb19335a59c22085ef8.png@942w_489h_progressive.webp'
  - name: '兔女郎时'
    path: './image/student_rank/'
    url: 'https://i0.hdslb.com/bfs/article/168813a13e5824e2c2264d10df048530d70ed601.png@942w_494h_progressive.webp'