image:
  - name: 'test'
    path: './image/some/'
    url: ''
    group: ''
  - name: 'test'
    path: './image/some/'
    url: ''
  - name: 'test'
    path: './image/student_rank/'
    url: ''