image:
  - name: 'test'
    path: './image/some/'
    url: ''
    group: ''
  - name: 'test'
    path: './image/some/'
    url: ''
  - name: 'mika银行'
    path: './image/some/'
    url: 'https://i0.hdslb.com/bfs/new_dyn/c1b9bf0fa49e237ae81b261a5d44882a425535005.png@1295w.webp'
  - name: 'test'
    path: './image/student_rank/'
    url: ''