image:
  - name: 'test'
    path: './image/some/'
    url: ''
    group: ''
  - name: 'test'
    path: './image/some/'
    url: ''
  - name: '角色简评'
    path: './image/some/'
    url: 'https://i0.hdslb.com/bfs/new_dyn/d176c55cc4666103b6585e75a6ccda70425535005.png@1295w.webp'
  - name: 'test'
    path: './image/student_rank/'
    url: ''
  - name: '堇'
    path: './image/student_rank/'
    url: 'https://i0.hdslb.com/bfs/article/3664cbe63c096a09cca7ec97af32020bec278da9.png@942w_489h_progressive.webp'
  - name: '艾米'
    path: './image/student_rank/'
    url: 'https://i0.hdslb.com/bfs/article/8ccec15a9eed7567cb0330645d1d55823a95f3b7.png@942w_488h_progressive.webp'
  - name: '日向'
    path: './image/student_rank/'
    url: 'https://i0.hdslb.com/bfs/article/d7aa3edfab938d14bfe8780276a1911f01c86339.png@942w_389h_progressive.webp'
  - name: '萌惠'
    path: './image/student_rank/'
    url: 'https://i0.hdslb.com/bfs/article/0d50b9078a8a43772204e0aefea8366b8df48858.png@942w_488h_progressive.webp'