image:
  - name: 'test'
    path: './image/some/'
    url: ''
    group: ''
  - name: '日服圣诞活动'
    path: './image/some/'
    url: 'https://i0.hdslb.com/bfs/article/314701eca55b51bf4afe364d67906266d8aed826.png@942w_414h_progressive.webp'
    group: '1'
  - name: '日服圣诞活动1'
    path: './image/some/'
    url: 'https://i0.hdslb.com/bfs/new_dyn/6bab374e513b5743be670539c966827f425535005.png@1295w.webp'
    group: '1'
  - name: '日服圣诞活动2'
    path: './image/some/'
    url: 'https://i0.hdslb.com/bfs/article/6ef8030cf6cc9cde1c990301e94b432d6a93a5e6.png@942w_261h_progressive.webp'
    group: '1'
  - name: 'test'
    path: './image/some/'
    url: ''
  - name: 'test'
    path: './image/student_rank/'
    url: ''
