image:
  - name: 'test'
    path: './image/some/'
    url: ''
    group: ''
    type: "vertical" # horizen or vertical
    source: '1'
  - name: 'test'
    path: './image/some/'
    url: ''
    source: '1'
  - name: 'test'
    path: './image/student_rank/'
    url: ''
    source: '1'
image:
  - name: 'test'
    path: './image/some/'
    url: ''
    group: ''
    type: "vertical" # horizen or vertical
    source: '1'
  - name: 'test'
    path: './image/some/'
    url: ''
    source: '1'
  - name: '碎片刷取'
    path: './image/some/'
    url: 'https://i0.hdslb.com/bfs/new_dyn/d371c32e1ba1f7e8c73683ee463fdc5f425535005.png@1048w_!web-dynamic.webp'
    source: '1'
  - name: 'test'
    path: './image/student_rank/'
    url: ''
    source: '1'