image:
  - name: 'test'
    path: './image/some/'
    url: ''
    group: ''
    type: "vertical" # horizen or vertical
    source: '1'
  - name: 'test'
    path: './image/some/'
    url: ''
    source: '1'
  - name: '国际服总力'
    path: './image/some/'
    url: 'https://i0.hdslb.com/bfs/new_dyn/744297e6bc666d52e04907f70f7e5bc7425535005.png@1036w_!web-dynamic.webp'
    source: '1'
  - name: 'test'
    path: './image/student_rank/'
    url: ''
    source: '1'
