image:
  - name: 'test'
    path: './image/some/'
    url: ''
    group: ''
    type: "vertical" # horizen or vertical
    source: '1'
  - name: 'test'
    path: './image/some/'
    url: ''
    source: '1'
  - name: '日服人权'
    path: './image/some/'
    url: 'https://i0.hdslb.com/bfs/new_dyn/f5a4d53ca0475426fa3798d8dac853b9425535005.png@1048w_!web-dynamic.avif'
    source: '1'
  - name: 'test'
    path: './image/student_rank/'
    url: ''
    source: '1'