image:
  - name: 'test'
    path: './image/some/'
    url: ''
    group: ''
  - name: 'test'
    path: './image/some/'
    url: ''
  - name: '国际服人权'
    path: './image/some/'
    url: 'https://i0.hdslb.com/bfs/new_dyn/c18e0e59ee197b3a0068f46b502aa554425535005.png@1295w.webp'
  - name: '日服人权'
    path: './image/some/'
    url: 'https://i0.hdslb.com/bfs/new_dyn/c18e0e59ee197b3a0068f46b502aa554425535005.png@1295w.webp'
  - name: '日服角色简评'
    path: './image/some/'
    url: 'https://i0.hdslb.com/bfs/new_dyn/9262f5680a2dd14268325f47a08f1017425535005.png@1295w.webp'
  - name: '角色简评'
    path: './image/some/'
    url: 'https://i0.hdslb.com/bfs/new_dyn/9262f5680a2dd14268325f47a08f1017425535005.png@1295w.webp'
  - name: 'test'
    path: './image/student_rank/'
    url: ''
