image:
  - name: 'test'
    path: './image/some/'
    url: ''
    group: ''
    type: "horizen" # horizen or vertical
  - name: 'test'
    path: './image/some/'
    url: ''
  - name: '2'
    path: './image/some/'
    url: 'https://i0.hdslb.com/bfs/article/80048c6e81899f85df72cf812e839124cb6af222.png@1256w_1198h_!web-article-pic.avif'
  - name: '3'
    path: './image/some/'
    url: 'https://i0.hdslb.com/bfs/article/72049b203a3111264c49a0260d62f4287802dc33.png@1256w_1946h_!web-article-pic.avif'
  - name: 'test'
    path: './image/student_rank/'
    url: ''