image:
  - name: 'test'
    path: './image/some/'
    url: ''
    group: ''
    type: "vertical" # horizen or vertical
    source: '1'
  - name: 'buff'
    path: './image/some/'
    url: 'https://i0.hdslb.com/bfs/article/942b65b9fcf5b7980c2f6c896c017c11425535005.jpg@1256w_1592h_!web-article-pic.avif'
    group: '1'
    type: "horizen" # horizen or vertical
    source: '1'
  - name: 'buff1'
    path: './image/some/'
    url: 'https://i0.hdslb.com/bfs/article/5a7cfb571e9f67faa93b3bf0906d7267425535005.jpg@1256w_1546h_!web-article-pic.avif'
    group: '1'
    type: "horizen" # horizen or vertical
    source: '1'
  - name: 'buff2'
    path: './image/some/'
    url: 'https://i0.hdslb.com/bfs/article/d08c73fef417baa6950530a6ea3b200f425535005.png@1256w_1682h_!web-article-pic.avif'
    group: '1'
    type: "horizen" # horizen or vertical
    source: '1'
  - name: 'test'
    path: './image/some/'
    url: ''
    source: '1'
  - name: '国际服室外寿司'
    path: './image/some/'
    url: 'https://i0.hdslb.com/bfs/new_dyn/d82f4140b2d21c4f5962048832c1bcec425535005.png@1048w_!web-dynamic.avif'
    source: '1'
  - name: 'test'
    path: './image/student_rank/'
    url: ''
    source: '1'