image:
  - name: 'test'
    path: './image/some/'
    url: ''
    group: ''
  - name: 'test'
    path: './image/some/'
    url: ''
  - name: '果惠'
    path: './image/student_rank/'
    url: 'https://i0.hdslb.com/bfs/article/7cc7105e722656c0961fc8995c0dd3bf8106dd65.png@942w_492h_progressive.webp'
  - name: 'test'
    path: './image/student_rank/'
    url: ''