grantedPermissionMap: 
  '*:*': 
    - console
  'net.diyigemt.arona:command.active': 
    - '*'
  'net.diyigemt.arona:command.gacha': 
    - '*'
  'net.diyigemt.arona:command.gacha_one': 
    - '*'
  'net.diyigemt.arona:command.gacha_multi': 
    - '*'
  'net.diyigemt.arona:command.gacha_dog': 
    - '*'
  'net.diyigemt.arona:command.gacha_reset': 
    - '*'
  'net.diyigemt.arona:command.gacha_history': 
    - '*'